In [1]:
# імпорт базових модулей
import numpy as np
import pandas as pd
# import matplotlib.pyplot as plt
# import seaborn as sns
from tqdm import tqdm
from pathlib import Path
import shutil
from pprint import pprint

# параметри виведення
pd.set_option("display.max_columns", 500) # кількість колонок
pd.set_option("display.max_rows", 1000) # кількість рядків
pd.set_option("display.max_colwidth", 300) # ширина колонок
pd.set_option("display.precision", 5) # кількість знаків після коми

# вимикаємо зайві попередження
import warnings
warnings.filterwarnings("ignore")

# друк всіх результатів в одній комірці а не тільки останнього
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# магічний метод для того щоб отримувати графіки біля комірок з кодом
# %matplotlib inline

In [5]:
# імпорт додаткових модулей

# import sqlite3
# import pyarrow as pa
# # from pyarrow import csv
# import pyarrow.parquet as pq
# import math

from sentence_transformers import SentenceTransformer

In [2]:
# data_dir = "data"
data_file = "data/arxiv_subset.parquet"
df = pd.read_parquet(data_file)
df['title+abstract'] = df['title'] + " [SEP] " + df['abstract']
df.info()
df.head(5)

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              10000 non-null  str
 1   title           10000 non-null  str
 2   abstract        10000 non-null  str
 3   authors         10000 non-null  str
 4   year            10000 non-null  int64
 5   category        10000 non-null  str
 6   title+abstract  10000 non-null  str
dtypes: int64(1), str(6)
memory usage: 17.7 MB

,id,title,abstract,authors,year,category,title+abstract
0,0704.0001,Calculation of prompt diphoton production cross sections at Tevatron and LHC energies,"A fully differential calculation in perturbative quantum chromodynamics is presented for the production of massive photon pairs at hadron colliders. All next-to-leading order perturbative contributions from quark-antiquark, gluon-(anti)quark, and gluon-gluon subprocesses are included, as well as...","BalázsC., BergerE. L., NadolskyP. M., YuanC. -P.",2007,hep-ph,Calculation of prompt diphoton production cross sections at Tevatron and LHC energies [SEP] A fully differential calculation in perturbative quantum chromodynamics is presented for the production of massive photon pairs at hadron colliders. All next-to-leading order perturbative contributions ...
1,0704.0002,Sparsity-certifying Graph Decompositions,"We describe a new algorithm, the $(k,\ell)$-pebble game with colors, and use it obtain a characterization of the family of $(k,\ell)$-sparse graphs and algorithmic solutions to a family of problems concerning tree decompositions of graphs. Special instances of sparse graphs appear in rigidity th...","StreinuIleana, TheranLouis",2007,math.CO,"Sparsity-certifying Graph Decompositions [SEP] We describe a new algorithm, the $(k,\ell)$-pebble game with colors, and use it obtain a characterization of the family of $(k,\ell)$-sparse graphs and algorithmic solutions to a family of problems concerning tree decompositions of graphs. Special i..."
2,0704.0003,The evolution of the Earth-Moon system based on the dark matter field fluid model,"The evolution of Earth-Moon system is described by the dark matter field fluid model proposed in the Meeting of Division of Particle and Field 2004, American Physical Society. The current behavior of the Earth-Moon system agrees with this model very well and the general pattern of the evolution ...",PanHongjun,2007,physics.gen-ph,"The evolution of the Earth-Moon system based on the dark matter field fluid model [SEP] The evolution of Earth-Moon system is described by the dark matter field fluid model proposed in the Meeting of Division of Particle and Field 2004, American Physical Society. The current behavior of the Ea..."
3,0704.0004,A determinant of Stirling cycle numbers counts unlabeled acyclic single-source automata,We show that a determinant of Stirling cycle numbers counts unlabeled acyclic single-source automata. The proof involves a bijection from these automata to certain marked lattice paths and a sign-reversing involution to evaluate the determinant.,CallanDavid,2007,math.CO,A determinant of Stirling cycle numbers counts unlabeled acyclic single-source automata [SEP] We show that a determinant of Stirling cycle numbers counts unlabeled acyclic single-source automata. The proof involves a bijection from these automata to certain marked lattice paths and a sign-reve...
4,0704.0005,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\alpha}$,"In this paper we show how to compute the $\Lambda_{\alpha}$ norm, $\alpha\ge 0$, using the dyadic grid. This result is a consequence of the description of the Hardy spaces $H^p(R^N)$ in terms of dyadic and special atoms.","Abu-ShammalaWael, TorchinskyAlberto",2007,math.CA,"From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\alpha}$ [SEP] In this paper we show how to compute the $\Lambda_{\alpha}$ norm, $\alpha\ge 0$, using the dyadic grid. This result is a consequence of the description of the Hardy spaces $H^p(R^N)$ in terms of dyadic and special atoms."

In [3]:
INPUT_FILE = "data/arxiv_subset.parquet"
OUTPUT_FILE = "embeddings/arxiv_embeddings.parquet"
# MODEL_NAME = "allenai/specter2_base"
MODEL_NAME = "sentence-transformers/allenai-specter"
BATCH_SIZE = 64

In [10]:
model = SentenceTransformer(MODEL_NAME)

In [17]:
def make_text(row: pd.Series) -> str:
    title = str(row["title"]).strip()
    abstract = str(row["abstract"]).strip()
    return f"{title} [SEP] {abstract}"


texts = [make_text(row) for _, row in df.iterrows()]

embeddings = model.encode(
    texts,
    batch_size=BATCH_SIZE,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True,
)

df["embedding"] = embeddings.tolist()
# df.to_parquet(OUTPUT_FILE, index=False)
# print(f"Saved {len(df)} embeddings to {OUTPUT_FILE}")

Batches:   1%|          | 2/313 [02:39<6:52:13, 79.53s/it]

KeyboardInterrupt:

In [15]:
embeddings

NameError: name 'embeddings' is not defined

In [14]:
    df["embedding"]

KeyError: 'embedding'

In [2]:
matrix = np.load('embeddings/embeddings.npy')
matrix.shape

(10000, 768)

In [3]:
matrix[0]

array([ 1.98680088e-02,  3.86331901e-02,  1.44202067e-02,  2.46090312e-02,
       -8.91747046e-03, -1.77954212e-02,  6.16089366e-02,  2.95052025e-02,
        1.57969613e-02, -6.06374303e-03,  2.13780161e-02, -2.19329447e-02,
        3.79580781e-02,  1.11837557e-03,  9.26020276e-03, -2.23652981e-02,
       -2.32699164e-03, -1.34612042e-02,  3.13074552e-02, -5.83511591e-03,
        2.56701768e-03, -9.88954026e-03, -4.02686559e-02,  2.48887185e-02,
       -3.40341888e-02,  5.74985147e-02, -2.28009764e-02,  3.60187367e-02,
       -2.18245853e-03,  1.38508501e-02,  2.11142357e-02, -3.55164744e-02,
        3.65358442e-02, -4.38768677e-02,  1.44484011e-03, -4.63505238e-02,
       -1.13630341e-02, -1.34549066e-02, -2.34865248e-02,  4.75003421e-02,
        3.14082317e-02, -1.37108630e-02,  1.04653155e-02, -3.36675607e-02,
       -1.40884193e-02,  3.20932567e-02,  1.59231685e-02,  3.68388966e-02,
        2.93653291e-02, -3.10645849e-02,  3.24346907e-02, -5.99899329e-02,
        5.23118675e-03,  6.25213683e-02,  1.86860953e-02, -8.10182095e-03,
        6.95255958e-03,  7.39018200e-03, -2.20858436e-02, -1.49663156e-02,
       -6.99842349e-03,  3.06622088e-02, -1.10867224e-03,  3.34483571e-03,
        4.33168635e-02, -9.39041562e-03,  1.50848851e-02,  3.13166939e-02,
        2.91013401e-02,  3.20905484e-02,  3.53378877e-02, -7.17190430e-02,
        1.78371817e-02,  2.12391429e-02,  2.20209584e-02, -1.93606857e-02,
       -1.76948868e-02,  5.67038022e-02, -6.76868185e-02, -3.19042467e-02,
        2.98661343e-03, -1.91555656e-02,  3.88836488e-02, -3.50796245e-02,
       -1.94512103e-02,  4.55672108e-03, -2.69633196e-02, -1.30543979e-02,
       -5.76618034e-03,  7.52610108e-03,  2.64813192e-02,  5.71089797e-03,
        8.04868247e-03, -6.59280596e-03,  1.11567974e-02,  8.58425745e-04,
        1.04031274e-02, -8.94745719e-03,  1.35773197e-02,  4.33024056e-02,
       -2.72192750e-02,  1.13022830e-02, -4.37500328e-02, -1.90470964e-02,
        2.66265869e-02, -1.19296731e-02, -2.29923025e-04, -2.08019186e-02,
       -1.84132569e-02, -4.21927422e-02,  1.82754360e-02, -1.85624361e-02,
       -1.16546117e-02,  4.23894357e-03, -1.06467828e-02, -2.55389209e-03,
       -2.33486295e-02, -2.90964767e-02, -2.04132050e-02, -3.47725046e-03,
        1.85258128e-02, -2.06291471e-02,  1.27451885e-02,  9.62823164e-03,
        1.57335903e-02,  9.86359268e-03,  5.51708089e-03,  1.98130612e-03,
        3.57181020e-02, -1.46196946e-03,  6.71674823e-03, -5.03418688e-03,
       -1.12148691e-02, -2.29635965e-02, -4.18882407e-02,  2.13906057e-02,
       -5.23588210e-02, -2.29827985e-02, -2.16778517e-02, -1.66115481e-02,
       -1.31465234e-02, -1.03877559e-02,  4.70931940e-02,  1.74178891e-02,
       -1.50301727e-02,  2.68871952e-02, -1.29464446e-02, -1.92632433e-02,
       -2.59543136e-02,  1.00071693e-03,  4.99863364e-02, -5.39749349e-03,
       -5.53077459e-02, -1.02755791e-02,  2.58949641e-02, -2.20171362e-02,
        1.73465908e-02, -5.96774416e-03, -5.30503877e-03, -2.67578010e-03,
       -1.83902495e-02, -2.95817852e-02,  8.93116370e-02, -1.85571518e-02,
       -5.93704544e-02,  2.17442885e-02,  3.84720080e-02, -1.94324125e-02,
        3.07617597e-02,  1.39990160e-02, -3.12544703e-02,  3.24490964e-02,
       -2.85732094e-03,  4.21597064e-02,  3.19112907e-03,  1.50327841e-02,
       -1.14269191e-02,  3.55685093e-02, -8.25871248e-03,  1.98027808e-02,
        6.78098947e-03,  7.99500942e-02, -1.63582768e-02, -1.73371788e-02,
        2.05897130e-02,  3.03301979e-02,  7.19997333e-03,  3.81259801e-04,
       -2.46235617e-02, -4.44600061e-02,  1.90792866e-02, -1.34085314e-02,
        2.38350406e-03, -3.57162505e-02, -4.01038155e-02, -7.71534815e-03,
       -7.34441075e-03, -5.42951841e-03,  2.73639355e-02,  6.47328570e-02,
       -2.03703716e-02, -2.40458660e-02, -2.24209367e-03,  1.98115595e-02,
        1.58099197e-02,  3.00232740e-03, -8.10657721e-03, -1.07273972e-02,
       -6.30120793e-03,  2.90987082e-02, -2.90038139e-02, -7.84529839e-03,
        1.28514795e-02, -6.18354883e-03, -6.16964791e-03,  3.09914071e-02,
       -7.00306473e-03,  2.44823117e-02, -3.23374718e-02,  2.10198425e-02,
        2.79025920e-02,  6.55669998e-03,  3.39888036e-02, -2.16455646e-02,
       -2.48303171e-02,  1.25676766e-02,  3.93249653e-03,  1.72927696e-02,
        2.58796439e-02,  6.77109580e-04,  1.01477653e-02, -3.84104066e-02,
       -1.76854841e-02, -7.45597109e-03, -1.64681505e-02, -8.52882266e-02,
        2.97377985e-02,  1.37411486e-02, -2.60498207e-02,  4.23538731e-03,
        2.07294561e-02,  2.06763446e-02, -4.55296449e-02, -3.73519771e-03,
        1.91908423e-02,  4.14497126e-03,  5.72570087e-03,  3.22278850e-02,
        2.99962703e-02,  1.65508781e-02,  4.26653996e-02, -2.52680257e-02,
       -3.59833166e-02, -1.60283782e-02,  1.47702661e-03,  4.95055281e-02,
        3.16209905e-02,  3.14120725e-02,  4.27678041e-02, -2.73057241e-02,
       -2.03418210e-02, -1.58260781e-02,  2.41697207e-03,  5.11404611e-02,
        3.08889449e-02,  1.78150330e-02, -2.98568048e-02, -3.15918550e-02,
        3.55914840e-03,  1.34737445e-02, -9.24889580e-04, -1.67896282e-02,
       -3.25326174e-02, -5.09290919e-02,  3.36112976e-02,  1.86660681e-02,
        2.73392759e-02, -5.90921659e-03,  7.50455912e-03, -4.61982377e-02,
        4.72976938e-02, -2.40976643e-02,  6.74756011e-04,  1.98520441e-02,
        3.00852116e-02, -3.25678922e-02, -2.65621534e-03, -2.31648553e-02,
        1.58719383e-02, -8.52310564e-03,  4.48154062e-02, -4.10581939e-02,
       -2.08073556e-02,  1.65325161e-02, -8.74715112e-03, -2.51033641e-02,
       -5.79858162e-02, -4.40850183e-02, -7.66620971e-03, -1.59660503e-02,
        2.76751313e-02,  1.00379121e-02,  7.10204011e-03,  5.14327595e-03,
       -5.92188444e-03,  1.76327750e-02,  1.23555714e-03, -2.78264028e-03,
        3.37725691e-02,  3.24412598e-03, -5.97960409e-03, -6.97226060e-05,
       -4.56839288e-03, -2.47781910e-02, -5.03029823e-02,  2.58868071e-03,
       -4.32473719e-02, -2.51644328e-02,  4.67324592e-02, -4.86215157e-03,
       -3.13834436e-02, -2.86139920e-02,  5.84061211e-03,  2.22341996e-02,
       -1.15469685e-02, -1.98682323e-02,  2.00545229e-02, -4.40591164e-02,
        1.02218846e-02, -1.21271824e-02, -1.53165264e-02, -1.65357776e-02,
        9.25892964e-03, -9.82660800e-03,  2.71011926e-02,  1.45179396e-02,
       -1.26532372e-02, -1.85458343e-02,  2.44856458e-02, -3.54871824e-02,
        1.42085245e-02,  2.75625400e-02, -4.72938269e-03, -1.54797919e-02,
        8.26830976e-03, -2.39412040e-02, -3.69264893e-02,  2.55613662e-02,
       -3.49925421e-02,  1.03090759e-02, -2.06591394e-02,  1.06775397e-02,
        1.17388954e-02,  7.02297688e-03, -4.24580239e-02, -1.64957661e-02,
       -1.23962332e-02, -1.08432816e-02,  1.76430475e-02,  2.45898999e-02,
        1.41002508e-02,  1.84069425e-02, -3.02835251e-03, -3.21315750e-02,
       -2.07150877e-02,  1.08738560e-02,  4.18372005e-02, -2.98302807e-02,
       -3.21085677e-02, -3.76543850e-02, -5.81003819e-03,  4.77578444e-03,
       -3.58872563e-02,  2.89262254e-02,  4.99609672e-03,  2.37325821e-02,
       -4.48974371e-02, -1.77740008e-02, -1.20781083e-02, -1.22040605e-04,
        8.82319268e-03,  1.73310321e-02, -1.64827835e-02, -9.93774552e-03,
        3.96797247e-02, -3.10048442e-02, -1.59347393e-02, -2.46643722e-02,
        9.95924696e-03,  9.62163135e-03,  2.09212676e-02,  4.65571657e-02,
       -8.27699713e-03,  3.12400199e-02,  2.08482295e-02, -3.46624525e-04,
       -3.19743045e-02, -2.29735561e-02,  8.06295313e-03,  1.28866127e-02,
        4.38028201e-02, -1.25126773e-02, -4.70721461e-02,  2.95532793e-02,
       -3.65755633e-02, -6.24217093e-04, -1.07845999e-02,  3.98380682e-02,
       -5.19203534e-03, -4.90136398e-03, -1.25965299e-02, -1.10453907e-02,
        4.09830511e-02, -8.68953415e-04, -2.56141517e-02, -3.34922373e-02,
       -2.02675462e-02,  5.44280894e-02,  1.35121476e-02,  1.06575191e-02,
        1.59849282e-02,  1.87731776e-02,  6.91394091e-01,  2.07577143e-02,
        3.33301239e-02,  3.49203846e-03,  4.42216219e-03,  6.61065150e-03,
       -2.16402654e-02,  8.97315424e-03, -3.89659517e-02,  2.65731458e-02,
        6.53459132e-02,  3.14244744e-03,  2.48919427e-03,  1.67932864e-02,
       -3.31663620e-03, -3.00031751e-02,  2.76894378e-03,  1.93355717e-02,
       -4.05574654e-04, -5.30251451e-02, -1.31524052e-03,  2.08827276e-02,
        2.18836907e-02,  4.40432280e-02, -1.38814179e-02,  3.51115428e-02,
        4.52217162e-02,  3.04081589e-02,  3.00138984e-02,  5.87524287e-03,
       -7.89624697e-04, -3.40665281e-02,  3.43089015e-03,  9.56048071e-03,
       -2.06826162e-02, -1.53095433e-02, -2.01215483e-02, -5.73793761e-02,
        1.03410948e-02,  2.90439595e-02,  2.59553693e-04,  1.46322930e-02,
       -3.95382335e-03, -2.21936591e-03,  1.46938618e-02,  1.67044830e-02,
       -1.86216645e-02,  2.11289208e-02, -2.04126555e-02, -2.73132268e-02,
       -3.80956046e-02,  3.55690345e-02,  9.02410224e-03, -2.65015825e-03,
        5.62475622e-03,  4.18058373e-02,  1.88067090e-02, -3.04202568e-02,
       -1.52271474e-02, -1.54230297e-02, -7.80287106e-03, -2.26486679e-02,
       -6.22358453e-03,  1.41008487e-02,  1.16741853e-02,  2.47179382e-02,
       -3.43853422e-02,  4.32172194e-02, -2.08102614e-02,  8.35680403e-03,
       -1.27985096e-02, -1.24715669e-02,  9.25019942e-03, -4.08029556e-02,
        9.10762988e-04,  2.07183715e-02, -2.41760095e-03, -6.52740616e-03,
       -2.96925493e-02,  1.57115478e-02,  2.45119650e-02, -3.44459787e-02,
       -2.10284721e-02,  7.59206899e-03, -4.35770815e-03, -2.37320326e-02,
       -6.54457696e-03, -3.86324599e-02, -3.82360478e-04,  2.24989429e-02,
       -2.87226569e-02, -2.81696003e-02, -5.95071167e-03, -1.52018191e-02,
       -6.07563443e-02,  7.51986727e-03,  4.11824621e-02, -1.39030172e-02,
       -1.52042578e-03, -2.16106814e-03,  1.50011014e-02, -6.61321403e-03,
       -1.79077201e-02, -3.09876669e-02,  5.92086092e-02,  3.43632139e-02,
       -2.35508122e-02, -3.54532152e-02,  3.03833410e-02, -1.56654399e-02,
       -3.83021608e-02,  4.17472981e-02,  6.00482384e-03, -1.96048785e-02,
       -4.21596458e-03, -2.44501010e-02,  2.33535767e-02, -2.31268462e-02,
        3.32278050e-02,  1.80661455e-02,  1.33281844e-02, -5.44852242e-02,
       -8.38190597e-03,  1.73922647e-02, -3.71590033e-02, -2.36222595e-02,
        2.61333585e-02, -3.40941548e-02, -1.55849531e-02,  2.71550491e-02,
        2.25842036e-02, -2.88660564e-02, -1.76430040e-03, -2.67027388e-03,
        2.35526077e-02, -2.96750180e-02,  4.98810634e-02, -6.03769943e-02,
        8.89928453e-03,  2.73933578e-02, -3.38905640e-02, -3.94092733e-03,
        1.05443560e-02, -6.00071214e-02, -1.17545463e-02,  2.68263015e-04,
       -4.56063449e-03, -9.64978151e-03,  1.01551665e-02,  1.55577101e-02,
        1.40158962e-02, -1.80465374e-02, -4.58254442e-02, -3.73817980e-03,
        1.32289892e-02,  2.46605347e-03,  1.36302188e-02, -2.09052730e-02,
       -5.77204069e-03, -1.09431203e-02,  2.16199532e-02,  3.83999422e-02,
        2.73480476e-03, -3.10709490e-03,  6.40058517e-03, -2.62476373e-02,
       -5.06066047e-02, -1.97910517e-03, -4.08501811e-02, -4.45229113e-02,
       -3.57492678e-02, -3.01742405e-02,  2.67022173e-03, -2.72591002e-02,
       -3.75238247e-02,  2.60141511e-02, -3.53308693e-02, -5.46396244e-03,
        4.43727337e-02,  2.08464242e-03, -3.59274559e-02, -5.32918237e-02,
       -1.21526234e-02,  3.31082493e-02,  8.27288907e-03, -5.37639065e-03,
        3.02227084e-02,  1.31427422e-02, -4.07791790e-03,  2.56809574e-02,
        1.85327493e-02, -1.35155516e-02, -1.15457252e-02, -2.76275985e-02,
        3.52817923e-02,  2.63529476e-02,  3.59239168e-02, -4.94097807e-02,
        7.06736464e-03,  1.23649724e-02,  2.27485821e-02, -9.22598131e-03,
        1.96689311e-02,  7.84730818e-03, -2.76582614e-02, -8.35695211e-03,
       -2.06202343e-02, -5.44636138e-03, -4.12453385e-03, -9.82952025e-03,
        5.71120472e-04,  4.64641973e-02,  1.16232149e-02, -3.94636244e-02,
       -2.14109197e-02,  1.09630348e-02, -3.90673913e-02,  1.06515642e-02,
        2.29832493e-02, -2.58455146e-02, -3.67983282e-02,  5.08692209e-03,
       -1.34412693e-02,  1.18319457e-02, -8.59309640e-03,  4.49538082e-02,
       -1.25470618e-02, -5.51673584e-02,  9.53890663e-03,  1.18238879e-02,
       -1.34668974e-02, -3.68537083e-02,  1.36506604e-02,  3.36077958e-02,
       -3.26367132e-02,  2.94334013e-02, -5.50654158e-03,  2.85511240e-02,
       -4.38763760e-02,  1.39869528e-03, -2.05248166e-02,  1.69195682e-02,
       -2.53762063e-02,  5.73144630e-02,  2.92593171e-03, -1.28823966e-02,
        7.47415982e-03, -2.04401147e-02,  8.36492982e-03,  7.50055350e-03,
        1.41652739e-02,  9.25611798e-03, -1.99721253e-04,  1.52842728e-02,
       -2.93632075e-02, -7.29995826e-03,  2.97137666e-02, -2.64119674e-02,
       -1.65811144e-02, -2.44678110e-02,  1.01733739e-02, -1.85832195e-02,
        1.98714118e-02,  8.54777580e-04, -3.41337472e-02, -2.55386010e-02,
       -2.39866804e-02,  3.61829102e-02,  7.69400503e-03, -4.13480587e-02,
        9.64513794e-03,  3.09472904e-02,  2.15320233e-02,  3.19125764e-02,
        2.19099279e-02,  1.88997984e-02,  2.11356115e-02,  5.20858588e-03,
        2.14993358e-02, -3.16788629e-02, -2.28845328e-02,  5.60205197e-03,
        1.80439483e-02, -1.52015062e-02,  1.35167204e-02, -1.47330696e-02,
       -3.27563062e-02,  6.31842688e-02, -1.54948868e-02,  6.11968385e-03,
        3.38581316e-02, -3.80972549e-02, -1.74753629e-02,  3.68229486e-03,
       -6.10708818e-03, -9.79504455e-03,  6.69940934e-03,  3.65356430e-02,
       -1.64479371e-02,  1.70364231e-02, -3.68511230e-02,  3.16085927e-02,
        9.48920424e-05, -1.37314098e-02,  2.25963928e-02,  6.09121919e-02,
        1.59149170e-02, -4.72277254e-02,  2.03728415e-02, -7.38194818e-03,
       -2.28867140e-02, -3.76503207e-02, -4.84008528e-02,  3.59614901e-02,
        3.07651907e-02,  5.87255042e-03,  5.79125481e-03, -7.16094812e-03,
        3.70937004e-03,  1.91708852e-03,  3.70094813e-02, -8.65446590e-03,
       -2.75621451e-02, -2.35603144e-03,  1.87519696e-02, -3.52578051e-02,
        1.37005476e-02, -4.78420965e-02, -3.88410464e-02, -1.88112669e-02,
        3.65515016e-02,  1.71678606e-02,  2.67573223e-02,  6.68389127e-02,
        2.67329328e-02,  1.16529232e-02,  8.58637318e-03, -2.49999054e-02,
       -4.07401882e-02,  1.25594502e-02, -1.09090907e-02, -4.73534539e-02,
       -3.12869437e-02,  1.07503624e-03, -9.30337515e-03, -5.23919575e-02],
      dtype=float32)

In [4]:
documents = pd.read_parquet("data/arxiv_subset.parquet")
documents.shape
documents.info()
documents.head(5)

(10000, 6)

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        10000 non-null  str
 1   title     10000 non-null  str
 2   abstract  10000 non-null  str
 3   authors   10000 non-null  str
 4   year      10000 non-null  int64
 5   category  10000 non-null  str
dtypes: int64(1), str(5)
memory usage: 9.3 MB

,id,title,abstract,authors,year,category
0,0704.0001,Calculation of prompt diphoton production cross sections at Tevatron and LHC energies,"A fully differential calculation in perturbative quantum chromodynamics is presented for the production of massive photon pairs at hadron colliders. All next-to-leading order perturbative contributions from quark-antiquark, gluon-(anti)quark, and gluon-gluon subprocesses are included, as well as...","BalázsC., BergerE. L., NadolskyP. M., YuanC. -P.",2007,hep-ph
1,0704.0002,Sparsity-certifying Graph Decompositions,"We describe a new algorithm, the $(k,\ell)$-pebble game with colors, and use it obtain a characterization of the family of $(k,\ell)$-sparse graphs and algorithmic solutions to a family of problems concerning tree decompositions of graphs. Special instances of sparse graphs appear in rigidity th...","StreinuIleana, TheranLouis",2007,math.CO
2,0704.0003,The evolution of the Earth-Moon system based on the dark matter field fluid model,"The evolution of Earth-Moon system is described by the dark matter field fluid model proposed in the Meeting of Division of Particle and Field 2004, American Physical Society. The current behavior of the Earth-Moon system agrees with this model very well and the general pattern of the evolution ...",PanHongjun,2007,physics.gen-ph
3,0704.0004,A determinant of Stirling cycle numbers counts unlabeled acyclic single-source automata,We show that a determinant of Stirling cycle numbers counts unlabeled acyclic single-source automata. The proof involves a bijection from these automata to certain marked lattice paths and a sign-reversing involution to evaluate the determinant.,CallanDavid,2007,math.CO
4,0704.0005,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\alpha}$,"In this paper we show how to compute the $\Lambda_{\alpha}$ norm, $\alpha\ge 0$, using the dyadic grid. This result is a consequence of the description of the Hardy spaces $H^p(R^N)$ in terms of dyadic and special atoms.","Abu-ShammalaWael, TorchinskyAlberto",2007,math.CA

In [5]:
len(documents)

10000

In [7]:
vectors_to_upsert = [
    {
        "id": documents.iloc[doc_idx]["id"],
        "values": matrix[doc_idx].tolist(),
        "metadata": {key: value for key, value in documents.iloc[doc_idx].items() if pd.notnull(value)},
    }
    for doc_idx in tqdm(range(0, 20), desc="Підготовка векторів до upsert")
]

Підготовка векторів до upsert: 100%|██████████| 20/20 [00:00<00:00, 3856.83it/s]

In [8]:
vectors_to_upsert[0]

{'id': '0704.0001',
 'values': [0.01986800879240036,
  0.03863319009542465,
  0.014420206658542156,
  0.024609031155705452,
  -0.008917470462620258,
  -0.017795421183109283,
  0.06160893663764,
  0.029505202546715736,
  0.01579696126282215,
  -0.006063743028789759,
  0.021378016099333763,
  -0.021932944655418396,
  0.03795807808637619,
  0.001118375570513308,
  0.009260202758014202,
  -0.022365298122167587,
  -0.002326991641893983,
  -0.013461204245686531,
  0.03130745515227318,
  -0.005835115909576416,
  0.0025670176837593317,
  -0.009889540262520313,
  -0.040268655866384506,
  0.024888718500733376,
  -0.03403418883681297,
  0.0574985146522522,
  -0.022800976410508156,
  0.0360187366604805,
  -0.0021824585273861885,
  0.01385085005313158,
  0.021114235743880272,
  -0.03551647439599037,
  0.03653584420681,
  -0.04387686774134636,
  0.0014448401052504778,
  -0.046350523829460144,
  -0.011363034136593342,
  -0.013454906642436981,
  -0.02348652482032776,
  0.04750034213066101,
  0.03140823170542717,
  -0.013710862956941128,
  0.010465315543115139,
  -0.033667560666799545,
  -0.014088419266045094,
  0.03209325671195984,
  0.015923168510198593,
  0.036838896572589874,
  0.029365329071879387,
  -0.031064584851264954,
  0.03243469074368477,
  -0.05998993292450905,
  0.005231186747550964,
  0.06252136826515198,
  0.018686095252633095,
  -0.008101820945739746,
  0.0069525595754384995,
  0.007390181999653578,
  -0.022085843607783318,
  -0.01496631558984518,
  -0.006998423486948013,
  0.030662208795547485,
  -0.0011086722370237112,
  0.003344835713505745,
  0.04331686347723007,
  -0.009390415623784065,
  0.015084885060787201,
  0.031316693872213364,
  0.029101340100169182,
  0.03209054842591286,
  0.035337887704372406,
  -0.07171904295682907,
  0.01783718168735504,
  0.02123914286494255,
  0.022020958364009857,
  -0.019360685721039772,
  -0.017694886773824692,
  0.056703802198171616,
  -0.06768681854009628,
  -0.03190424665808678,
  0.002986613428220153,
  -0.01915556564927101,
  0.038883648812770844,
  -0.03507962450385094,
  -0.019451210275292397,
  0.004556721076369286,
  -0.02696331962943077,
  -0.013054397888481617,
  -0.005766180343925953,
  0.00752610107883811,
  0.026481319218873978,
  0.005710897967219353,
  0.00804868247359991,
  -0.006592805963009596,
  0.011156797409057617,
  0.0008584257448092103,
  0.010403127409517765,
  -0.008947457186877728,
  0.01357731968164444,
  0.04330240562558174,
  -0.027219275012612343,
  0.0113022830337286,
  -0.043750032782554626,
  -0.019047096371650696,
  0.0266265869140625,
  -0.01192967314273119,
  -0.00022992302547208965,
  -0.02080191858112812,
  -0.018413256853818893,
  -0.042192742228507996,
  0.018275436013936996,
  -0.0185624361038208,
  -0.011654611676931381,
  0.0042389435693621635,
  -0.01064678281545639,
  -0.0025538920890539885,
  -0.023348629474639893,
  -0.02909647673368454,
  -0.02041320502758026,
  -0.0034772504586726427,
  0.01852581277489662,
  -0.020629147067666054,
  0.012745188549160957,
  0.009628231637179852,
  0.015733590349555016,
  0.009863592684268951,
  0.005517080891877413,
  0.0019813061226159334,
  0.035718102008104324,
  -0.001461969455704093,
  0.006716748233884573,
  -0.005034186877310276,
  -0.01121486909687519,
  -0.022963596507906914,
  -0.04188824072480202,
  0.021390605717897415,
  -0.05235882103443146,
  -0.022982798516750336,
  -0.021677851676940918,
  -0.016611548140645027,
  -0.013146523386240005,
  -0.010387755930423737,
  0.04709319397807121,
  0.017417889088392258,
  -0.015030172653496265,
  0.02688719518482685,
  -0.012946444563567638,
  -0.019263243302702904,
  -0.025954313576221466,
  0.0010007169330492616,
  0.0499863363802433,
  -0.005397493485361338,
  -0.055307745933532715,
  -0.010275579057633877,
  0.02589496411383152,
  -0.022017136216163635,
  0.017346590757369995,
  -0.005967744160443544,
  -0.005305038765072823,
  -0.0026757800951600075,
  -0.018390249460935593,
  -0.029581785202026367,
  0.0893116369843483,
  -0.018557151779532433,
  -0.05937045440077782,
  0.021744288504123688,
  0.0384720079600811,
  -0.019432412460446358,
  0.030761759728193283,
  0.013999016024172306,
  -0.031254470348358154,
  0.03244909644126892,
  -0.0028573209419846535,
  0.042159706354141235,
  0.003191129071637988,
  0.015032784081995487,
  -0.011426919139921665,
  0.03556850925087929,
  -0.008258712477982044,
  0.01980278082191944,
  0.006780989468097687,
  0.07995009422302246,
  -0.016358276829123497,
  -0.01733717881143093,
  0.020589713007211685,
  0.030330197885632515,
  0.0071999733336269855,
  0.0003812598006334156,
  -0.024623561650514603,
  -0.044460006058216095,
  0.019079286605119705,
  -0.013408531434834003,
  0.0023835040628910065,
  -0.03571625053882599,
  -0.040103815495967865,
  -0.007715348154306412,
  -0.007344410754740238,
  -0.005429518409073353,
  0.027363935485482216,
  0.0647328570485115,
  -0.020370371639728546,
  -0.02404586598277092,
  -0.002242093672975898,
  0.019811559468507767,
  0.01580991968512535,
  0.003002327401190996,
  -0.008106577210128307,
  -0.010727397166192532,
  -0.006301207933574915,
  0.02909870818257332,
  -0.029003813862800598,
  -0.007845298387110233,
  0.012851479463279247,
  -0.006183548830449581,
  -0.0061696479097008705,
  0.030991407111287117,
  -0.0070030647329986095,
  0.02448231168091297,
  -0.03233747184276581,
  0.021019842475652695,
  0.027902591973543167,
  0.006556699983775616,
  0.03398880362510681,
  -0.02164556458592415,
  -0.024830317124724388,
  0.012567676603794098,
  0.003932496532797813,
  0.017292769625782967,
  0.025879643857479095,
  0.0006771095795556903,
  0.010147765278816223,
  -0.038410406559705734,
  -0.017685484141111374,
  -0.0074559710919857025,
  -0.016468150541186333,
  -0.08528822660446167,
  0.029737798497080803,
  0.013741148635745049,
  -0.026049820706248283,
  0.004235387314110994,
  0.02072945609688759,
  0.020676344633102417,
  -0.045529644936323166,
  -0.0037351977080106735,
  0.019190842285752296,
  0.0041449712589383125,
  0.0057257008738815784,
  0.032227884978055954,
  0.029996270313858986,
  0.016550878062844276,
  0.042665399610996246,
  -0.02526802569627762,
  -0.03598331660032272,
  -0.016028378158807755,
  0.0014770266134291887,
  0.049505528062582016,
  0.03162099048495293,
  0.031412072479724884,
  0.042767804116010666,
  -0.02730572409927845,
  -0.020341821014881134,
  -0.01582607813179493,
  0.0024169720709323883,
  0.05114046111702919,
  0.03088894486427307,
  0.017815032973885536,
  -0.029856804758310318,
  -0.031591854989528656,
  0.0035591484047472477,
  0.013473744504153728,
  -0.0009248895803466439,
  -0.016789628192782402,
  -0.03253261744976044,
  -0.05092909187078476,
  0.033611297607421875,
  0.018666068091988564,
  0.027339275926351547,
  -0.0059092165902256966,
  0.007504559122025967,
  -0.04619823768734932,
  0.04729769378900528,
  -0.024097664281725883,
  0.0006747560109943151,
  0.0198520440608263,
  0.030085211619734764,
  -0.03256789222359657,
  -0.002656215336173773,
  -0.02316485531628132,
  0.015871938318014145,
  -0.008523105643689632,
  0.04481540620326996,
  -0.041058193892240524,
  -0.020807355642318726,
  0.016532516106963158,
  -0.008747151121497154,
  -0.025103364139795303,
  -0.0579858161509037,
  -0.04408501833677292,
  -0.00766620971262455,
  -0.015966050326824188,
  0.02767513133585453,
  0.010037912055850029,
  0.007102040108293295,
  0.005143275950103998,
  -0.005921884439885616,
  0.017632775008678436,
  0.0012355571379885077,
  -0.002782640280202031,
  0.03377256914973259,
  0.003244125982746482,
  -0.005979604087769985,
  -6.972260598558933e-05,
  -0.004568392876535654,
  -0.02477819100022316,
  -0.050302982330322266,
  0.002588680712506175,
  -0.043247371912002563,
  -0.02516443282365799,
  0.04673245921730995,
  -0.004862151574343443,
  -0.031383443623781204,
  -0.028613992035388947,
  0.005840612109750509,
  0.022234199568629265,
  -0.01154696848243475,
  -0.019868232309818268,
  0.020054522901773453,
  -0.04405911639332771,
  0.010221884585916996,
  -0.012127182446420193,
  -0.015316526405513287,
  -0.01653577759861946,
  0.009258929640054703,
  -0.009826608002185822,
  0.027101192623376846,
  0.014517939649522305,
  -0.012653237208724022,
  -0.018545834347605705,
  0.024485645815730095,
  -0.035487182438373566,
  0.014208524487912655,
  0.027562540024518967,
  -0.004729382693767548,
  -0.015479791909456253,
  0.008268309757113457,
  -0.023941203951835632,
  -0.03692648932337761,
  0.025561366230249405,
  -0.03499254211783409,
  0.010309075936675072,
  -0.02065913937985897,
  0.010677539743483067,
  0.011738895438611507,
  0.007022976875305176,
  -0.04245802387595177,
  -0.01649576611816883,
  -0.012396233156323433,
  -0.010843281634151936,
  0.017643047496676445,
  0.0245898999273777,
  0.014100250788033009,
  0.018406942486763,
  -0.0030283525120466948,
  -0.03213157504796982,
  -0.02071508765220642,
  0.010873856022953987,
  0.04183720052242279,
  -0.02983028069138527,
  -0.03210856765508652,
  -0.03765438497066498,
  -0.005810038186609745,
  0.004775784444063902,
  -0.035887256264686584,
  0.028926225379109383,
  0.004996096715331078,
  0.023732582107186317,
  -0.04489743709564209,
  -0.017774000763893127,
  -0.01207810826599598,
  -0.00012204060476506129,
  0.008823192678391933,
  0.01733103208243847,
  -0.01648278348147869,
  -0.00993774551898241,
  0.03967972472310066,
  -0.03100484423339367,
  -0.015934739261865616,
  -0.024664372205734253,
  0.009959246963262558,
  0.009621631354093552,
  0.020921267569065094,
  0.046557165682315826,
  -0.00827699713408947,
  0.03124001994729042,
  0.02084822952747345,
  -0.0003466245252639055,
  -0.03197430446743965,
  -0.02297355607151985,
  0.008062953129410744,
  0.012886612676084042,
  0.04380282014608383,
  -0.01251267734915018,
  -0.0470721460878849,
  0.029553279280662537,
  -0.0365755632519722,
  -0.0006242170929908752,
  -0.010784599930047989,
  0.039838068187236786,
  -0.0051920353434979916,
  -0.004901363980025053,
  -0.01259652990847826,
  -0.011045390740036964,
  0.04098305106163025,
  -0.0008689534151926637,
  -0.02561415173113346,
  -0.03349223732948303,
  -0.0202675461769104,
  0.054428089410066605,
  0.013512147590517998,
  0.010657519102096558,
  0.015984928235411644,
  0.01877317763864994,
  0.6913940906524658,
  0.02075771428644657,
  0.033330123871564865,
  0.0034920384641736746,
  0.004422162193804979,
  0.00661065150052309,
  -0.021640265360474586,
  0.008973154239356518,
  -0.03896595165133476,
  0.026573145762085915,
  0.06534591317176819,
  0.003142447443678975,
  0.0024891942739486694,
  0.01679328642785549,
  -0.003316636197268963,
  -0.030003175139427185,
  0.0027689437847584486,
  0.01933557167649269,
  -0.00040557465399615467,
  -0.05302514508366585,
  -0.001315240515395999,
  0.020882727578282356,
  0.021883690729737282,
  0.04404322803020477,
  -0.01388141792267561,
  0.03511154279112816,
  0.0452217161655426,
  0.030408158898353577,
  0.030013898387551308,
  0.0058752428740262985,
  -0.0007896246970631182,
  -0.03406652808189392,
  0.003430890152230859,
  0.0095604807138443,
  -0.020682616159319878,
  -0.01530954334884882,
  -0.02012154832482338,
  -0.05737937614321709,
  0.010341094806790352,
  0.029043959453701973,
  0.00025955369346775115,
  0.01463229302316904,
  -0.0039538233540952206,
  -0.0022193659096956253,
  0.014693861827254295,
  0.016704482957720757,
  -0.018621664494276047,
  0.02112892083823681,
  -0.020412655547261238,
  -0.027313226833939552,
  -0.03809560462832451,
  0.03556903451681137,
  0.009024102240800858,
  -0.0026501582469791174,
  0.005624756217002869,
  0.04180583730340004,
  0.018806708976626396,
  -0.03042025677859783,
  -0.015227147378027439,
  -0.015423029661178589,
  -0.007802871055901051,
  -0.02264866791665554,
  -0.006223584525287151,
  0.014100848697125912,
  0.011674185283482075,
  0.024717938154935837,
  -0.03438534215092659,
  0.04321721941232681,
  -0.020810261368751526,
  0.00835680402815342,
  -0.012798509560525417,
  -0.012471566908061504,
  0.009250199422240257,
  -0.040802955627441406,
  0.0009107629884965718,
  0.020718371495604515,
  -0.0024176009465008974,
  -0.00652740616351366,
  -0.029692549258470535,
  0.015711547806859016,
  0.02451196499168873,
  -0.034445978701114655,
  -0.02102847211062908,
  0.007592068985104561,
  -0.004357708152383566,
  -0.023732032626867294,
  -0.006544576957821846,
  -0.038632459938526154,
  -0.0003823604783974588,
  0.02249894291162491,
  -0.02872265689074993,
  -0.028169600293040276,
  -0.005950711667537689,
  -0.015201819129288197,
  -0.060756344348192215,
  0.007519867271184921,
  0.04118246212601662,
  -0.013903017155826092,
  -0.0015204257797449827,
  -0.002161068143323064,
  0.015001101419329643,
  -0.006613214034587145,
  -0.017907720059156418,
  -0.03098766691982746,
  0.05920860916376114,
  0.034363213926553726,
  -0.023550812155008316,
  -0.03545321524143219,
  0.030383341014385223,
  -0.015665439888834953,
  -0.038302160799503326,
  0.04174729809165001,
  0.006004823837429285,
  -0.01960487850010395,
  -0.0042159645818173885,
  -0.02445010095834732,
  0.02335357666015625,
  -0.023126846179366112,
  0.03322780504822731,
  0.018066145479679108,
  0.013328184373676777,
  -0.054485224187374115,
  -0.00838190596550703,
  0.017392264679074287,
  -0.03715900331735611,
  -0.023622259497642517,
  0.026133358478546143,
  -0.034094154834747314,
  -0.015584953129291534,
  0.02715504914522171,
  0.022584203630685806,
  -0.028866056352853775,
  -0.0017643003957346082,
  -0.002670273883268237,
  0.023552607744932175,
  -0.029675018042325974,
  0.049881063401699066,
  -0.06037699431180954,
  0.008899284526705742,
  0.027393357828259468,
  -0.03389056399464607,
  -0.00394092733040452,
  0.01054435595870018,
  -0.06000712141394615,
  -0.01175454631447792,
  0.0002682630147319287,
  -0.00456063449382782,
  -0.009649781510233879,
  0.010155166499316692,
  0.015557710081338882,
  0.014015896245837212,
  -0.018046537414193153,
  -0.04582544416189194,
  -0.0037381798028945923,
  0.013228989206254482,
  0.002466053469106555,
  0.013630218803882599,
  -0.020905273035168648,
  -0.005772040691226721,
  -0.01094312034547329,
  0.021619953215122223,
  0.038399942219257355,
  0.0027348047588020563,
  -0.003107094904407859,
  0.006400585174560547,
  -0.02624763734638691,
  -0.05060660466551781,
  -0.0019791051745414734,
  -0.04085018113255501,
  -0.04452291131019592,
  -0.03574926778674126,
  -0.030174240469932556,
  0.0026702217292040586,
  -0.02725910022854805,
  -0.03752382472157478,
  0.02601415105164051,
  -0.035330869257450104,
  -0.005463962443172932,
  0.04437273368239403,
  0.0020846424158662558,
  -0.03592745587229729,
  -0.05329182371497154,
  -0.012152623385190964,
  0.03310824930667877,
  0.008272889070212841,
  -0.0053763906471431255,
  0.030222708359360695,
  0.013142742216587067,
  -0.004077917896211147,
  0.02568095736205578,
  0.018532749265432358,
  -0.013515551574528217,
  -0.011545725166797638,
  -0.027627598494291306,
  0.035281792283058167,
  0.02635294757783413,
  0.03592391684651375,
  -0.04940978065133095,
  0.007067364640533924,
  0.01236497238278389,
  0.022748582065105438,
  -0.009225981310009956,
  0.019668931141495705,
  0.007847308181226254,
  -0.027658261358737946,
  -0.008356952108442783,
  -0.020620234310626984,
  -0.005446361377835274,
  -0.004124533850699663,
  -0.009829520247876644,
  0.0005711204721592367,
  0.04646419733762741,
  0.011623214930295944,
  -0.039463624358177185,
  -0.021410919725894928,
  0.010963034816086292,
  -0.03906739130616188,
  0.010651564225554466,
  0.02298324927687645,
  -0.025845514610409737,
  -0.036798328161239624,
  0.005086922086775303,
  -0.013441269285976887,
  0.011831945739686489,
  -0.008593096397817135,
  0.044953808188438416,
  -0.012547061778604984,
  -0.05516735836863518,
  0.009538906626403332,
  0.011823887936770916,
  -0.013466897420585155,
  -0.03685370832681656,
  0.013650660403072834,
  0.03360779583454132,
  -0.03263671323657036,
  0.02943340130150318,
  -0.005506541579961777,
  0.028551124036312103,
  -0.04387637600302696,
  0.0013986952835693955,
  -0.02052481658756733,
  0.016919568181037903,
  -0.025376206263899803,
  0.05731446295976639,
  0.0029259317088872194,
  -0.012882396578788757,
  0.007474159821867943,
  -0.0204401146620512,
  0.00836492981761694,
  0.0075005535036325455,
  0.014165273867547512,
  0.009256117977201939,
  -0.00019972125301137567,
  0.015284272842109203,
  -0.029363207519054413,
  -0.007299958262592554,
  0.029713766649365425,
  -0.02641196735203266,
  -0.016581114381551743,
  -0.02446781098842621,
  0.010173373855650425,
  -0.01858321949839592,
  0.019871411845088005,
  0.0008547775796614587,
  -0.03413374722003937,
  -0.025538600981235504,
  -0.023986680433154106,
  0.036182910203933716,
  0.007694005034863949,
  -0.041348058730363846,
  0.009645137935876846,
  0.030947290360927582,
  0.021532023325562477,
  0.03191257640719414,
  0.02190992794930935,
  0.01889979839324951,
  0.021135611459612846,
  0.005208585876971483,
  0.021499335765838623,
  -0.03167886286973953,
  -0.022884532809257507,
  0.005602051969617605,
  0.018043948337435722,
  -0.015201506204903126,
  0.01351672038435936,
  -0.014733069576323032,
  -0.03275630623102188,
  0.06318426877260208,
  -0.01549488678574562,
  0.006119683850556612,
  0.03385813161730766,
  -0.03809725493192673,
  -0.017475362867116928,
  0.003682294860482216,
  -0.006107088178396225,
  -0.009795044548809528,
  0.006699409335851669,
  0.03653564304113388,
  -0.01644793711602688,
  0.017036423087120056,
  -0.036851122975349426,
  0.031608592718839645,
  9.48920423979871e-05,
  -0.013731409795582294,
  0.022596392780542374,
  0.06091219186782837,
  0.0159149169921875,
  -0.04722772538661957,
  0.020372841507196426,
  -0.007381948176771402,
  -0.022886713966727257,
  -0.037650320678949356,
  -0.04840085282921791,
  0.035961490124464035,
  0.030765190720558167,
  0.005872550420463085,
  0.005791254807263613,
  -0.007160948123782873,
  0.0037093700375407934,
  0.0019170885207131505,
  0.037009481340646744,
  -0.008654465898871422,
  -0.02756214514374733,
  -0.0023560314439237118,
  0.018751969560980797,
  -0.03525780513882637,
  0.013700547628104687,
  -0.04784209653735161,
  -0.03884104639291763,
  -0.018811266869306564,
  0.03655150160193443,
  0.01716786064207554,
  0.026757322251796722,
  0.06683891266584396,
  0.026732932776212692,
  0.011652923189103603,
  0.008586373180150986,
  -0.02499990537762642,
  -0.04074018821120262,
  0.01255945023149252,
  -0.010909090749919415,
  -0.04735345393419266,
  -0.03128694370388985,
  0.001075036241672933,
  -0.009303375147283077,
  -0.052391957491636276],
 'metadata': {'id': '0704.0001',
  'title': 'Calculation of prompt diphoton production cross sections at Tevatron and   LHC energies',
  'abstract': 'A fully differential calculation in perturbative quantum chromodynamics is presented for the production of massive photon pairs at hadron colliders. All next-to-leading order perturbative contributions from quark-antiquark, gluon-(anti)quark, and gluon-gluon subprocesses are included, as well as all-orders resummation of initial-state gluon radiation valid at next-to-next-to-leading logarithmic accuracy. The region of phase space is specified in which the calculation is most reliable. Good agreement is demonstrated with data from the Fermilab Tevatron, and predictions are made for more detailed tests with CDF and DO data. Predictions are shown for distributions of diphoton pairs produced at the energy of the Large Hadron Collider (LHC). Distributions of the diphoton pairs from the decay of a Higgs boson are contrasted with those produced from QCD processes at the LHC, showing that enhanced sensitivity to the signal can be obtained with judicious selection of events.',
  'authors': 'BalázsC., BergerE. L., NadolskyP. M., YuanC. -P.',
  'year': np.int64(2007),
  'category': 'hep-ph'}}

In [2]:
df = pd.read_parquet("data/arxiv_subset.parquet")
df['abstract_length'] = df['abstract'].fillna("").str.len()

df.sort_values(by='abstract_length', ascending=False, inplace=True)

In [3]:
df.iloc[0:30]

,id,title,abstract,authors,year,category,abstract_length
7848,0705.3846,The SN 1987A Link to Gamma-Ray Bursts,"Early measurements of SN 1987A indicate a beam/jet (BJ) which hit polar ejecta (PE) to produce the ""Mystery Spot"" (MS). The SN flash takes an extra 8 d to hit the MS, and this was confirmed at 2e39 ergs/s in the optical at day 8. A ramp in luminosity starting near day 10 indicates particles from...",MiddleditchJohn,2007,astro-ph,1872
987,0704.0988,Evidence for a Massive Protocluster in S255N,S255N is a luminous far-infrared source that contains many indications of active star formation but lacks a prominent near-infrared stellar cluster. We present mid-infrared through radio observations aimed at exploring the evolutionary state of this region. Our observations include 1.3mm continu...,"CyganowskiC. J., BroganC. L., HunterT. R.",2007,astro-ph,1866
1300,0704.1301,IRAS 18317-0757: A Cluster of Embedded Massive Stars and Protostars,"We present high-resolution, multiwavelength continuum and molecular-line images of the massive star forming region IRAS 18317-0757. The IR through mm spectral energy distribution can be approximated by a two-temperature model (25 and 63 K) with a total luminosity of approximately log(L/Lsun)=5.2...","HunterT. R., ZhangQ., SridharanT. K.",2007,astro-ph,1858
2444,0704.2445,Multi-Color Photometry of the Galactic Globular Cluster M75 = NGC 6864. A New Sensitive Metallicity Indicator and the Position of the Horizontal Branch in UV,"We carry out and analyze new multi-color photometry of the Galactic globular cluster (GC) M75 in UBVI and focus on the brighter sequences of the color- magnitude diagram (CMD), with particular emphasis on their location in U-based CMD. Specifically, we study the level both of the horizontal (HB)...","KravtsovV., AlcainoG., MarconiG., AlvaradoF.",2007,astro-ph,1857
8345,0705.4343,A Systematic Study of the Final Masses of Gas Giant Planets,"We construct an analytic model for the rate of gas accretion onto a planet embedded in a protoplanetary disk as a function of planetary mass, disk viscosity, disk scale height, and unperturbed surface density in order to study the long-term accretion and final masses of gas giant planets. We fir...","TanigawaT., IkomaM.",2007,astro-ph,1854
2195,0704.2196,Absolute Calibration and Characterization of the Multiband Imaging Photometer for Spitzer. II. 70 micron Imaging,The absolute calibration and characterization of the Multiband Imaging Photometer for Spitzer (MIPS) 70 micron coarse- and fine-scale imaging modes are presented based on over 2.5 years of observations. Accurate photometry (especially for faint sources) requires two simple processing steps beyon...,"GordonKarl D., EngelbrachtCharles W., FaddaDario, StansberryJohn, WachterStefanie, FrayerDave T., RiekeGeorge, Noriega-CrespoAlberto, LatterWilliam B., YoungErick",2007,astro-ph,1853
798,0704.0799,Spin Evolution of Accreting Neutron Stars: Nonlinear Development of the R-mode Instability,The nonlinear saturation of the r-mode instability and its effects on the spin evolution of Low Mass X-ray Binaries (LMXBs) are modeled using the triplet of modes at the lowest parametric instability threshold. We solve numerically the coupled equations for the three mode amplitudes in conjuncti...,"BondarescuRuxandra, TeukolskySaul A., WassermanIra",2007,astro-ph,1851
3099,0704.3100,The Origin of the Galaxy Mass-Metallicity Relation and Implications for Galactic Outflows,"(Abridged) Using cosmological hydrodynamic simulations in combination with analytic modeling, we show that the galaxy stellar mass-metallicity relation (MZR) provides strong constraints on galactic outflows across cosmic time. We compare three outflow models: No outflows, a ""constant wind"" (cw) ...","FinlatorK., DaveR.",2007,astro-ph,1849
5208,0705.1206,The SSS phase of RS Ophiuchi observed with Chandra and XMM-Newton I.: Data and preliminary Modeling,"The phase of Super-Soft-Source (SSS) emission of the sixth recorded outburst of the recurrent nova RS Oph was observed twice with Chandra and once with XMM-Newton. The observations were taken on days 39.7, 54.0, and 66.9 after outburst. We confirm a 35-sec period on day 54.0 and found that it or...","NessJ. -U., StarrfieldS., BeardmoreA. P., BodeM. F., DrakeJ. J., EvansA., GehrzR. D., GoadM. R., Gonzalez-RiestraR., HauschildtP.",2007,astro-ph,1849
8141,0705.4139,Our Peculiar Motion Away from the Local Void,The peculiar velocity of the Local Group of galaxies manifested in the Cosmic Microwave Background dipole is found to decompose into three dominant components. The three components are clearly separated because they arise on distinct spatial scales and are fortuitously almost orthogonal in their...,"TullyR. Brent, ShayaEdward J., KarachentsevIgor D., CourtoisHelene M., KocevskiDale D., RizziLuca, PeelAlan",2007,astro-ph,1849
5047,0705.1045,Conjectures on exact solution of three - dimensional (3D) simple orthorhombic Ising lattices,"We report the conjectures on the three-dimensional (3D) Ising model on simple orthorhombic lattices, together with the details of calculations for a putative exact solution. Two conjectures, an additional rotation in the fourth curled-up dimension and the weight factors on the eigenvectors, are ...",ZhangZhi-dong,2007,cond-mat.stat-mech,1848
2234,0704.2235,Swift observations of GRB 060614: an anomalous burst with a well behaved afterglow,"GRB 060614 is a remarkable GRB observed by Swift with puzzling properties, which challenge current progenitor models. The lack of any bright SN down to very strict limits and the vanishing spectral lags are typical of short GRBs, strikingly at odds with the long (102s) duration of this event. He...","ManganoV., HollandS. T., MalesaniD., TrojaE., ChincariniG., ZhangB., La ParolaV., BrownP. J., BurrowsD. N., CampanaS.",2007,astro-ph,1847
3914,0704.3915,NBODY meets stellar population - The HYDE-PARC Project,N-body simulations give us a rough idea of how the shape of a simulated object appears in three-dimensional space. From an observational point of view this may give us a misleading picture. The faint stars may be the most common stars in the system but the morphological information obtained by o...,"BorchAndrea, SpurzemRainer, HurleyJarrod",2007,astro-ph,1847
9202,0706.0516,The Kinematics of the Ultra-Faint Milky Way Satellites: Solving the Missing Satellite Problem,"We present Keck/DEIMOS spectroscopy of stars in 8 of the newly discovered ultra-faint dwarf galaxies around the Milky Way. We measure the velocity dispersions of Canes Venatici I and II, Ursa Major I and II, Coma Berenices, Hercules, Leo IV and Leo T from the velocities of 18 - 214 stars in each...","SimonJoshua D., GehaMarla",2007,astro-ph,1847
8063,0705.4061,High energy afterglows and flares from Gamma-Ray Burst by Inverse Compton emission,"We perform a detailed study of inverse Compton (IC) emission for a fireball undergoing external shock (ES) in either a uniform or a wind-like interstellar medium, and assess the relative importance of IC and synchrotron emissions. We determine the primary model parameters driving the IC to synch...","GalliA., PiroL.",2007,astro-ph,1847
4879,0705.0877,Dependence of CMI Growth Rates on Electron Velocity Distributions and Perturbation by Solitary Waves,We calculate growth rates and corresponding gains for RX and LO mode radiation associated with the cyclotron maser instability for parameterized horseshoe electron velocity distributions. The velocity distribution function was modeled to closely fit the electron distribution functions observed i...,"MutelR. L., PetersonW. M., JaegerT. R., ScudderJ. D.",2007,astro-ph,1844
4167,0705.0165,Is Modified Gravity Required by Observations? An Empirical Consistency Test of Dark Energy Models,"We apply the technique of parameter-splitting to existing cosmological data sets, to check for a generic failure of dark energy models. Given a dark energy parameter, such as the energy density Omega_Lambda or equation of state w, we split it into two meta-parameters with one controlling geometr...","WangSheng, HuiLam, MayMorgan, HaimanZoltan",2007,astro-ph,1844
656,0704.0657,The Boundary Conditions of the Heliosphere: Photoionization Models Constrained by Interstellar and In Situ Data,"The boundary conditions of the heliosphere are set by the ionization, density and composition of inflowing interstellar matter. Constraining the properties of the Local Interstellar Cloud (LIC) at the heliosphere requires radiative transfer ionization models. We model the background interstellar...","SlavinJonathan D., FrischPriscilla C.",2007,astro-ph,1843
7403,0705.3401,A model for the Globular Cluster extreme anomalies,"In spite of the efforts made in the latest years, still there is no comprehensive explanation for the chemical anomalies of globular cluster stars. Among these, the most striking is oxygen depletion, which reaches values down to [O/Fe]~-0.4 in most clusters, but in M13 it goes down to less than ...","D'AntonaF., VenturaP.",2007,astro-ph,1842
9959,0706.1273,Multicolor observations of the afterglow of the short/hard GRB 050724,"New information on short/hard gamma-ray bursts (GRBs) is being gathered thanks to the discovery of their optical and X-ray afterglows. However, some key aspects are still poorly understood, including the collimation level of the outflow, the duration of the central engine activity, and the prope...","MalesaniD., CovinoS., D'AvanzoP., D'EliaV., FugazzaD., PiranomonteS., BalloL., CampanaS., StellaL., TagliaferriG.",2007,astro-ph,1842
8616,0705.4614,"The Mira variable S Ori: Relationships between the photosphere, molecular layer, dust shell, and SiO maser shell at 4 epochs","We present the first multi-epoch study that includes concurrent mid-infrared and radio interferometry of an oxygen-rich Mira star. We obtained mid-infrared interferometry of S Ori with VLTI/MIDI at four epochs between December 2004 and December 2005. We concurrently observed v=1, J=1-0 (43.1 GHz...","WittkowskiM., BoboltzD. A., OhnakaK., DriebeT., ScholzM.",2007,astro-ph,1842
6380,0705.2378,"X-ray emission from PSR J1809-1917 and its pulsar wind nebula, possibly associated with the TeV gamma-ray source HESS J1809-193",We detected X-ray emission from the 50-kyr-old pulsar J1809-1917 and resolved its pulsar wind nebula (PWN) with Chandra. The pulsar spectrum fits PL+BB model with the photon index of 1.2 and the BB temperature of 2 MK for n_{H}=0.7\times 10^{22} cm^{-2}. The luminosities are(4\pm 1)\times 10^{31...,"KargaltsevO., PavlovG. G.",2007,astro-ph,1841
9335,0706.0649,Spherically symmetric problem on the brane and galactic rotation curves,We investigate the braneworld model with induced gravity to clarify the role of the cross-over length scale \ell in the possible explanation of the dark-matter phenomenon in astrophysics and in cosmology. Observations of the 21 cm line from neutral hydrogen clouds in spiral galaxies reveal that ...,"ViznyukAlexander, ShtanovYuri",2007,gr-qc,1841
3067,0704.3068,"Ages for illustrative field stars using gyrochronology: viability, limitations and errors","We here develop an improved way of using a rotating star as a clock, set it using the Sun, and demonstrate that it keeps time well. This technique, called gyrochronology, permits the derivation of ages for solar- and late-type main sequence stars using only their rotation periods and colors. The...",BarnesSydney A.,2007,astro-ph,1840
9765,0706.1079,Co-orbital Oligarchy,"We present a systematic examination of the changes in semi-major axis caused by the mutual interactions of a group of massive bodies orbiting a central star in the presence of eccentricity dissipation. For parameters relevant to the oligarchic stage of planet formation, dynamical friction keeps ...","CollinsBenjamin F., SariRe'em",2007,astro-ph,1840
8645,0705.4643,The Supernova Channel of Super-AGB Stars,"We study the late evolution of solar metallicity stars in the transition region between white dwarf formation and core collapse. This includes the super-asymptotic giant branch (super-AGB, SAGB) stars, which have massive enough cores to ignite carbon burning and form an oxygen-neon (ONe) core. T...","PoelarendsA. J. T., HerwigF., LangerN., HegerA.",2007,astro-ph,1839
8719,0706.0033,Improved constraints on dark energy from Chandra X-ray observations of the largest relaxed galaxy clusters,"We present constraints on the mean matter density, Omega_m, dark energy density, Omega_de, and the dark energy equation of state parameter, w, using Chandra measurements of the X-ray gas mass fraction (fgas) in 42 hot (kT>5keV), X-ray luminous, dynamically relaxed galaxy clusters spanning the re...","AllenS. W., RapettiD. A., SchmidtR. W., EbelingH., MorrisG., FabianA. C.",2007,astro-ph,1837
3610,0704.3611,UV Star Formation Rates in the Local Universe,"We measure star formation rates of ~50,000 optically-selected galaxies in the local universe (z~0.1), spanning a range from gas-rich dwarfs to massive ellipticals. We obtain dust-corrected SFRs by fitting the GALEX (UV) and SDSS (optical) photometry to a library of population synthesis models th...","SalimSamir, RichR. Michael, CharlotStéphane, BrinchmannJarle, JohnsonBenjamin D., SchiminovichDavid, SeibertMark, MalleryRyan, HeckmanTimothy M., ForsterKarl",2007,astro-ph,1836
5934,0705.1932,Spin Effects in Quantum Chromodynamics and Recurrence Lattices with Multi-Site Exchanges,"In this thesis, we consider some spin effects in QCD and recurrence lattices with multi-site exchanges. Main topic of our manuscript are critical phenomena in spin systems defined on the recurrence lattices. Main tool of our approach is the method of recursive (hierarchical) lattices. We apply t...",AnanikyanLev,2007,cond-mat.stat-mech,1836
3265,0704.3266,Rotation and activity of pre-main-sequence stars,"We present a study of rotation (vsini) and chromospheric activity (Halpha EW) based on an extensive set of high-resolution optical spectra obtained with MIKE on the 6.5m Magellan Clay telescope. Our targets are 74 F-M dwarfs in the young stellar associations Eta Cha, TW Hydrae, Beta Pic, and Tuc...","ScholzAleks, CoffeyJaime, BrandekerAlexis, JayawardhanaRay",2007,astro-ph,1835